# Generated by Django 3.2.6 on 2021-08-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=50)),
                ('phono', models.BigIntegerField()),
                ('date_of_birth', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('adharno', models.CharField(max_length=50)),
            ],
        ),
    ]
