# Generated by Django 3.2.6 on 2021-08-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productdetails', models.CharField(max_length=50)),
                ('sellername', models.CharField(max_length=50)),
                ('manufacturer_name', models.CharField(max_length=50)),
                ('manufacturing_date', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
