# Generated by Django 3.2.6 on 2021-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('carno', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('phono', models.CharField(max_length=50)),
            ],
        ),
    ]
