# Generated by Django 3.2.6 on 2021-08-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketer_name', models.CharField(max_length=50)),
                ('matchone_score', models.CharField(max_length=50)),
                ('matchtwo_score', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('batting_style', models.CharField(max_length=50)),
                ('bowling_style', models.CharField(max_length=50)),
            ],
        ),
    ]
